require("prototypes.configuration")

require("prototypes.assault-rifles")
require("prototypes.assault-ammo")
require("prototypes.sniper-rifles")
require("prototypes.sniper-ammo")
require("prototypes.railgun-rifles")
require("prototypes.railgun-ammo")
require("prototypes.rocket-launchers")
require("prototypes.rocket-ammo")
require("prototypes.rocket-projectiles")