require("configuration")
require("prototypes.technologies")

require("prototypes.assault-rifles")
require("prototypes.assault-ammo")
require("prototypes.sniper-rifles")
require("prototypes.sniper-ammo")
require("prototypes.rocket-launchers")
require("prototypes.rocket-ammo")
require("prototypes.rocket-projectiles")
require("prototypes.walls")
require("prototypes.gates")
require("prototypes.radars")
require("prototypes.gun-turret")
require("prototypes.laser-turret")
require("prototypes.flamethrower-turret")